### ISSUE TITLE
EEA Crosschain Interop WG - Presentation

### ISSUE THREAD

**Issue by anaisofranc** [eea-oasis/L2#15]
The Crosschain Interop WG is planning to present its Crosschain Interop Protocol to the L2 group on Wednesday April 6. It will be an opportunity to ask questions and to understand how the specs meets the requirements of the L2 group' s use case.

Proposed timeslots are 
Tuesday April 5, 6:30am Brisbane / Monday April 4, 4:30pm New York
Thursday April 7, 6:30am Brisbane / Wednesday April 6 4:30pm New York

**Comment by dshaw** [comment]
Wednesday April 6 1:30pm San Francisco / Wednesday April 6 4:30pm New York / Thursday April 7, 6:30am Brisbane
