### ISSUE TITLE
Define L2 Interop Interface standards - engage EEA crosschain interop working group

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/L2#20]
Define a Standard Interface for L2 Interoperability Transactions including non-EVM compatible/equivalent L2s such as zk-L2s as well as better trust guarantees rather than just trust notifications.

Some starting Points  for discussions:

- [EIP-4844](https://www.eip4844.com/)
- [Baseline Protocol Standard: Interoperability Section](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#55-bpi-integration)

**Comment by bossyuansu** [comment]
i'd be interested. one interesting point to cover: general framework regarding the TX finality of each L2 constructions and its impact on finality of the cross L2 operations.

**Comment by Therecanbeonlyone1969** [comment]
Maybe the definition of finality and then categorize by L2

**Comment by Therecanbeonlyone1969** [comment]
EEA Interop WG messaging interface draft spec ... we should dicsuss in the WG: https://entethalliance.github.io/crosschain-interoperability/draft_crosschain_techspec_messaging.html

**Comment by anaisofranc** [comment]
The EEA Crosschain Interop WG will confirm if they can present and share latest status with the L2 group on November the 16th at 10am ET. I will update this issue accordingly.

**Comment by Therecanbeonlyone1969** [comment]
Now a duplicate issue. Closing.
