### ISSUE TITLE
Crosschain WG x L2 Group

### ISSUE THREAD

**Issue by anaisofranc** [eea-oasis/L2#30]
We discussed that the L2 group would be open to present and update on the status of its work to the Crosschain Interop WG. Would Wednesday November 2nd at 2100 UTC | 5PM EDT work ?

**Comment by anaisofranc** [comment]
@Therecanbeonlyone1969 - I made a mistake, the date should be November 09th instead of November 2nd. Can you confirm that it works for you: November 9th at 2100 UTC | 5PM EDT ? Thank you, Anaïs

**Comment by Therecanbeonlyone1969** [comment]
> @Therecanbeonlyone1969 - I made a mistake, the date should be November 09th instead of November 2nd. Can you confirm that it works for you: November 9th at 2100 UTC | 5PM EDT ? Thank you, Anaïs

@anaisofranc yes that works.

**Comment by anaisofranc** [comment]
Meeting invite was sent today to @Therecanbeonlyone1969 .

**Comment by Therecanbeonlyone1969** [comment]
Update meeting occurred. Will report out on 11/16/2022 L2 WG meeting
