### ISSUE TITLE
Crosschain WG x L2 Group

### ISSUE THREAD

**Issue by anaisofranc** [eea-oasis/L2#31]
We discussed that the Crosschain Interop WG would present and update on the status of its work to the L2 group. 
Weijia Wang is no longer available to present on Nov 16. However, he can present on Nov 30th. 

@Therecanbeonlyone1969  : Would 10:30am EST, Nov.30 work ?

**Comment by Therecanbeonlyone1969** [comment]
That works. Will include in Agenda

**Comment by Therecanbeonlyone1969** [comment]
Will happen during 1/25/23 L2 WG meeting

**Comment by Therecanbeonlyone1969** [comment]
completed
