### ISSUE TITLE
Should the group reach out to the Espresso Systems team ?

### ISSUE THREAD

**Issue by anaisofranc** [eea-oasis/L2#45]
Article: https://hackmd.io/@EspressoSystems/SharedSequencing

Maybe the group could invite them to present and discuss what they are proposing and working on ?

**Comment by Therecanbeonlyone1969** [comment]
@anaisofranc can you provide a bit more background and rationale, please?

**Comment by anaisofranc** [comment]
Please disregard this issue. It is no longer relevant.
