### ISSUE TITLE
L2 Data Transaction Fees

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/L2#48]
How to define and include L2 Data Transaction Fees into a transaction

**Comment by Therecanbeonlyone1969** [comment]
Suggestions on the Transaction Data Fee to be discussed with WG:

- Transaction Data is part of the Execution Fee as we defined in the Transaction Data Fee spec (#43) 
- The transaction data fee must follow the same visibility and verification requirements as the transaction fee components in #43 
-  The data transaction fee calculation algorithm or method must be published
- In addition to the transaction data fee the gas price, the gas cost, and data size for the transaction must be displayed. **Question: Should we only display what will end up on the L1 or L1 and L2?**
- Gas price calculation or method must be visible and verifiable. Same requirement as we had for the transaction data fee. **Question: Should we define separate requirements for gas price oracles vs. calculations (based on oracles)? If yes, what are the key differences?**

**Comment by Therecanbeonlyone1969** [comment]
Offchain Labs:
- On the L2: View of estimated [L1 gas price](https://docs.arbitrum.io/arbos/l1-pricing#adjusting-the-l1-gas-basefee) (a calculated number based on the actual cost paid by a sequencer to amortize the cost over time) per byte.
- Sequencer charges the user a certain amount. And dynamically adjusts the gas price if the sequencer is over or underpaid on the L1 data. 
- Sequencer estimates the compression factor until the batch is compressed. Therefore, the amount of bytes in the gas price per byte varies between estimation and posting value. 
- Need to address the difference between the amount a user is charged and what the sequencer pays in a consistent manner

Link as general reference on the issue: https://research.arbitrum.io/t/l1-calldata-data-pricing-sequencer-reimbursement-fee-pool-model/107

**Comment by 0x000hx** [comment]
Metis fee calculation (September 2023)
1. Gas calculations formula
  STEP 1, Calculate IntrinsicGas:
  
  gas = contractCreation && isHomestead ? params.TxGasContractCreation[53000] : params.TxGas[21000]
  nz = non_zero_byte_length(data)
  nonZeroGas = isEIP2028?  params.TxDataNonZeroGasEIP2028[16] : params.TxDataNonZeroGasFrontier[68]
  gas += nz * nonZeroGas
  z = len(data) - nz
  gas += z * params.TxDataZeroGas[4]

  STEP 2, read l1FeeInL2:
  (st is StateTransition)
  NOTE: st.l1FeeInL2 can be set in GasOracle contract
  
  STEP 3, use gas:
  st.useGas(gas)
  st.useGas(st.l1FeeInL2)

  FINAL:
  totalCost = gas + st.l1FeeInL2
  
  *Protocol params const, you can find it in l2geth/params/protocol_params.go

**Comment by Therecanbeonlyone1969** [comment]
Suggested set of initial requirements for the L2 Transaction Fee spec:

1. An L2 Transaction Data Fee MUST be part of the L2 Execution Fee as defined in the Transaction Data Fee specification (https://github.com/eea-oasis/L2/pull/43) and MUST be displayed separately.

2. An L2 Transaction Data Fee MUST indicate to be part of the L2 Execution Fee.

3.  An L2 Transaction Data Fee MUST be displayed separately from the L2 Execution Fee.

4. An L2 Transaction Data Fee MUST follow the same visibility and verification requirements as the L2 Execution Fee.

5. An L2 Transaction Data Fee SHOULD/MUST be separated into the L2 and the L1 fee component.

6. An L2 data transaction fee calculation algorithm or method MUST be published and verifiable.

7. The gas price, the gas cost, and the L2 transaction data size as part of an L2 Transaction Data Fee derivation MUST be displayed as part of an L2 Transaction Data Fee display both combined and separated by L2 and L1 components.

8. The gas price calculation or method used in an L2 Transaction Data fee MUST be published and verifiable.

9. The utilized L1 and L2 gas price SHOULD/MUST indicate if it was derived based on a calculation or a Gas Price Data Oracle, or a combination of both.

10. If there is an L2 Data Transaction Fee Refund, it MUST follow the L2 Transaction Data Fee specification. 

Any additional requirements?

**Comment by Therecanbeonlyone1969** [comment]
Closing because this issue is included in PR #43 which was merged.
