### ISSUE TITLE
L2/Sidechain <-> L1 and L2/Sidechain <-> L2/Sidechain Bridging Digital Assets with Residuals 

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/L2#6]
**Problem Statement:**

In the current state of bridging digital assets such as ERC20 tokens or NFTs between L1s, or L2s/Sidechains, or between L1s and L2s/Sidechains, assets are immobilized on the origin L1/L2/Sidechains and then instantiated on the target L1/L2/Sidechain. Note, to simplify wording, we will use origin and target network going forward.

This approach is fine if the digital asset is unencumbered. Unencumbered in this context means that there are no business rules associated with the digital asset that infer rights or obligations such as stable coins or simple NFTs. Examples of digital assets that infer rights to the owner, and are, thus, not unencumbered, are digital assets that are earning the owner residual payments/asset grants such as dividend-paying Equities paying dividends, Bonds, Annuities, Asset-Backed Securities, Royalties, etc.  

Encumbered digital assets can currently not be transferred between networks because of the business logic e.g. bond payment schedule and the state of the digital asset with respect to that business logic e.g. the number of payments made, the number of payments left, etc because the transfer would break the connection between the asset, and the rights or obligations associated with it, unless the digital asset, its business logic, and its entire state were to be transferred across the bridge.

**Question to be answered:**

How can encumbered digital assets be transferred between networks?   

**My 2 Wei:**

Completely unbaked

- Immobilize asset on the origin network, but allow the asset state to be updatable from the target network
- Transfer entire asset state and, virtual state machine (VSM) framework, from origin to target network 
- Instantiate VSM with the asset state in a container e.g. docker and register it with the target network, for example as a special precompile contract, and allow for calls to the container based on the established syntax on the origin network to be executed in the container, and the computed result to be included in the target network state
- the container, via the bridge, updates the state of the asset on the origin chain. This would require a fraud-proof through e.g. an accompanying zkp. 

Thoughts?

**Comment by Therecanbeonlyone1969** [comment]
@dshaw @kthomas ... please, add others so they are aware of the discussion

**Comment by tasdienes** [comment]
Two thoughts:
1. It would be good to post this on ethresear.ch for feedback (perhaps after a little more baking?)
2. The container idea make me think of Cartesi.  Is that a good fit?

**Comment by Therecanbeonlyone1969** [comment]
> Two thoughts:
> 
> 1. It would be good to post this on ethresear.ch for feedback (perhaps after a little more baking?)

We should collect a few more thoughts here.

> 2. The container idea make me think of Cartesi.  Is that a good fit?

@tasdienes I will email a link out to this issue together with the meeting minutes and ask for their feedback and contribution. Wish I had their github handles.

**Comment by Therecanbeonlyone1969** [comment]
A new token standard for interest-bearing assets has been developed by the Tribe DAO, one of our close partners: https://ethereum-magicians.org/t/eip-4626-yield-bearing-vault-standard/7900 from Rahul

**Comment by Therecanbeonlyone1969** [comment]
**Proposed Eth Magician Post**
Currently bridging digital assets such as ERC20 tokens or NFTs between networks (L1 <-> L1, L1 <-> L2, L2 <-> L2, L1 <-> sidechain), immobilizes the assets on the origin network and then instantiates them on the target network.

This approach works well if the digital asset has no associated business rules associated that infer rights or obligations to asset owners such as stable coins or simple NFTs. Examples of important digital assets that infer rights to the digital asset owner are residual payments/asset grants such as dividend-paying equities, bonds, annuities, asset-backed securities, digital assets with royalties, etc.

Unfortunately, such digital assets can currently not be transferred between networks because a transfer would break the connection between the asset, and the rights or obligations associated with it.

Given the importance of residual bearing digital assets in traditional finance and the emerging proliferation of DeFi assets that mimic traditional assets such as bonds or asset-backed securities while more and more value is locked in bridges and L2s, what would be possible solution approaches to this conundrum?

**Proposed Eth Research Post**
Currently bridging digital assets such as ERC20 tokens or NFTs between networks (L1 <-> L1, L1 <-> L2, L2 <-> L2, L1 <-> sidechain), immobilizes the assets on the origin network and then instantiates them on the target network.

This approach works well if the digital asset has no associated business rules associated that infer rights or obligations to asset owners such as stable coins or simple NFTs. Examples of important digital assets that infer rights to the digital asset owner are residual payments/asset grants such as dividend-paying equities, bonds, annuities, asset-backed securities, digital assets with royalties, etc.

Unfortunately, such digital assets can currently not be transferred between networks because a transfer would break the connection between the asset, and the rights or obligations associated with it.

Given the importance of residual bearing digital assets in traditional finance and the emerging proliferation of DeFi assets that mimic traditional assets such as bonds or asset-backed securities while more and more value is locked in bridges and L2s, what would be possible solution approaches to this conundrum?

**Identified Solution Challenges**

Using the simple example of Bond on Ethereum paying on a schedule in DAI, we outline some of the challenges

1. Since Alice (payor) of the scheduled bond payments is generally unaware that Bob (payee) moved a bond from Ethereum to Solana, Alice would send payment to the Bond smart contract with Bob's address. Since Bob is no longer the owner of the bond, but rather the bridge contract is the payment would fail
2. If the bond contract were still aware that Bob was the payee, then the smart contract could still accept a bond payment but the payment would be owned by the bridge contract.
3. The previous bullet means that when the bond is locked in the bridge, the expected DAI bond payments must be instantiated on the Solana side in the Bond contract, now with Bob the owner of both the Bond token and the wrapped DAI
4. This means that when a payment is received into the Ethereum bond contract, the bridge network must be notified through an event of the payment and mint the payment amount as wrapped DAI on the DAI bridge contract on the Solana side, for Bob. That is problematic, because, there is no corresponding DAI in the bridge on the Ethereum side because it is associated with the Ethereum bond contract. This means that Bob's WDAI on Solana would be worthless.  Therefore, the payment amount in DAI can only be minted as an Ethereum IOU in the Solana Bond contract, since the DAI cannot be taken out of the Solana smart contract. That means the DAI payments the bondholder receives are useless on the Solana side. That is naturally not desirable.
5. If the bond is traded to Claire on Solana, Claire is now eligible to receive bond payments and no longer Bob. That means that after Claire purchased the Bond, the bridge network must create a placeholder for Claire's payment to be received on the Ethereum side. That also means that Alice needs to know that she needs to send her bond payments indexed to Claire and not Bob. And once Claire receives a payment, the bridge network needs to create the same Ethereum DAI IOU on the Solana side. And so forth for every ownership change   

And this is for a simple case of a bond, royalties for example, where the payments are mostly independent of token ownership and typically more than one party receives a portion of the payment are more complex because not all payments need to be bridged. However, the value of the digital asset is dependent on payment flows.

Generally speaking, it is unclear how to port complex digital assets between networks when the value of the asset depends on payments on the origin network but the asset is traded on the target network. The feedback and thoughts from the community would be greatly appreciated,

[Blog Link with the above copy of Eth Magician and Eth Research Post](https://docs.google.com/document/d/1RCq9XfH8daEQ_djabRIkXXn0LBYdiNBUV9NiH5lZdT4/edit?usp=sharing) (only title so far).

**Comment by drinkcoffee** [comment]
The EEA are working towards a standard that will do this. It is moving the GPACT protocol towards standardisation. GPACT provides crosschain (blockchain, sidechain, rollup, etc) function calls: call trees across chains. The protocol is specifically designed to address the type of use-case you describe. 
https://arxiv.org/abs/2011.12783
https://github.com/ConsenSys/gpact
https://entethalliance.github.io/crosschain-interoperability/   Note that the standards are WIP, and as such are not yet public.

**Comment by Therecanbeonlyone1969** [comment]
@drinkcoffee Thank you for sharing. Very interesting, 

Question(s): In the above example of a Bond, Alice must make a payment to Bob on Chain A, but Bob has sold the Bond to Claire on Chain B. How does Alice know to pay Claire unless Alice is always online and monitors chain A for ownership change events? And how is Claire made aware that she was paid on Chain A if Claire does not constantly monitor chain B? Also, say the payment is made in ETH on Chain A and is now WETH on Chain B, how does a user know the difference from WETH from the Bondcontract to WETH from another bridge contract? I could now create a WETH/WETH swap pair with a AMM on chain B with varying prices for WETH in one contract vs. another contract because of different liquidity in the trading pair, even though the value of ETH on chain A is unchanged. This would allow an attacker to censor the value of a particular type of WETH vs another WETH, no?  What happens if Claire moves the Bond to Chain C and sells it to David? Do we then have to synchronize across different call trees across different GPACT implementations operated by different relay networks?

**Comment by drinkcoffee** [comment]
@Therecanbeonlyone1969  I have seen this and will write a comprehensive response tomorrow.

**Comment by drinkcoffee** [comment]
I think it might help to create an example. I think it matches your example. 

There is an ERC 721 token that represents the rights to royalties for some music. The ERC 721 is issued on the Chain A. The ERC 721 is owned by Alice. The owner of the ERC 721 is paid royalties in DAI. 
Alice uses a bridge to do a crosschain transfer to Chain B, thus moving the ERC 721 token to Chain B. 
Alice sells the ERC 721 token to Bob.
Bob sells the token to Claire. 
Claire moves the token to Chain C.
Claire sells the token to David.
When royalties are now paid, they should be paid to David. 

Whether the royalties are paid on Chain A, where the token was first issued, or where the token is, on Chain C, I think is going to come down to the agreement put in place when the token was issued.

**Comment by drinkcoffee** [comment]
The EEA Crosschain Interoperability Working Group (https://entethalliance.github.io/crosschain-interoperability/) are working on a set of standards that define the Crosschain Protocol Stack. The protocol stack defines a Crosschain Application Layer, a Crosschain Function Call Layer, and a Crosschain Messaging Layer. General Purpose Atomic Crosschain Transaction (GPACT) protocol fits into the function call layer. The idea is that applications can be built on top of this protocol stack, without application developers having to implement the whole protocol stack.

The working drafts are currently private. They are likely to become public in the coming days. Interop testing based on the drafts is set to happen in Q2 this year. The latest working drafts are here:

https://github.com/EntEthAlliance/crosschain-interoperability/blob/5fe542f0f4be29eba38ce827f63a332643adcf29/working-docs/techspec/citf_technical_specification_messaging.htm 
https://github.com/EntEthAlliance/crosschain-interoperability/blob/5fe542f0f4be29eba38ce827f63a332643adcf29/working-docs/techspec/citf_technical_specification_function.htm

**Comment by drinkcoffee** [comment]
The GPACT protocol could solve the use-case in the following way:

- Create a royalties contract on Chain A. 
- Have a function in the contract to allow other the address of ERC 721 contracts on other chains to be blockchains, and their blockchain ID to be registered
- Have a function to register the address of bridge contracts on Chain A. That is, so that the royalties contract can detect when an ERC 721 is owned on Chain A by a bridge contract.
- When a royalties payment is to be made, the function in the royalties contract would determine where the ERC 721 token is. That is, is the token owned in the ERC 721 contract on Chain A by a bridge or a normal user? If it owned by a bridge, then check the ERC 721 contracts on the other blockchains to see if the token is there. This checking is done by doing a function call across blockchains that sees who is the owner of the ERC 721 on the other chain. This will result in an address of the owner. The owner is then paid the royalty payment.

Note that GPACT allows arbitrary call execution trees across blockchains. As such, you could tweak this application of the technology.

**Comment by drinkcoffee** [comment]
btw, I would like to join your forthcoming meeting. However, unfortunately, the call is at 1am my time zone.

**Comment by drinkcoffee** [comment]
The draft specifications are now available here: 
https://entethalliance.github.io/crosschain-interoperability/draft_crosschain_techspec.html

**Comment by Therecanbeonlyone1969** [comment]
@drinkcoffee thank you for your very thoughtful contributions.

The royalty example is probably not the best because there is typically more than one recipient and, if the asset is derived from another asset, payments are also made to the creator(s) of the original asset. However, your example illustrates another issue. A royalty-bearing asset can never be just transferred since this would open the door to royalty circumvention schemes, it must be purchased. The bridge contracts and contracts on other chains would have to be whitelisted as ok to own the asset and one would need special transfer functions etc. These functions all create additional attack vectors e.g. which contracts can be trusted.

I think the Bond example is simpler and illustrates the issue I see. If the residual payment is initiated off-chain (Issuer pays bondholder). When the Issuer is not aware of an ownership change, the GPACT protocol must keep track of the entire ownership history in case payments are received for a former owner by an issuer unaware that ownership has changed, and route them appropriately.

I have also been wondering how this would work in the typical L1 <-> L2 and L2 <-> L2 scenarios this WG is interested in with zk- or even zk-zk-rollups. Would that not require that rollups actually do not rollup anymore but update each "bridged" contract separately to keep atomicity, or could you do batch updates where the proof-of-atomicity of a transaction sequence updating the state is done with a zkp validated by the target contract?

**Comment by drinkcoffee** [comment]
> I think the Bond example is simpler and illustrates the issue I see. If the residual payment is initiated off-chain (Issuer pays bondholder). When the Issuer is not aware of an ownership change, the GPACT protocol must keep track of the entire ownership history in case payments are received for a former owner by an issuer unaware that ownership has changed, and route them appropriately.

This routing of payments is something that the application contract sitting on top of GPACT protocol could do.

**Comment by drinkcoffee** [comment]
> I have also been wondering how this would work in the typical L1 <-> L2 and L2 <-> L2 scenarios this WG is interested in with zk- or even zk-zk-rollups. Would that not require that rollups actually do not rollup anymore but update each "bridged" contract separately to keep atomicity, or could you do batch updates where the proof-of-atomicity of a transaction sequence updating the state is done with a zkp validated by the target contract?

A zk Rollup uses a zero knowledge proof to prove that a set of state transitions are correct based on a set of transactions. 

In the Crosschain Protocol Stack, the GPACT crosschain control contract on each chain works with applications contracts on the chain. The application contracts hold the state. The messaging layer is used to prove events were emitted from a certain chain. 

What I think you are saying is, for the zk rollup scenario, how do you prove to a target chain that a transaction on a source rollup resulted in a contract emitting an event? That is a good question. It is related to the messaging layer, and not the function call layer of the Crosschain Protocol Stack. Obviously, you could have threshold signing of the event. However, as you say, it might be possible to construct some zkp to show that the event was emitted by a contract based on a transaction.

**Comment by Therecanbeonlyone1969** [comment]
Blog published by EEA. Close issue for now.
